name: CI

on:
  push:
    branches:
      - "main"
      - "develop"
      - "deploy/**"
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

  test-unit-and-integration:
    strategy:
      fail-fast: true
    name: Test Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.3.1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test --match-path "test/{unit,integration}/**/*.sol"
        id: test
  
  test-invariant:
    strategy:
      fail-fast: true
    name: Test Invariant
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.3.1

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test --match-path "test/invariant/**/*.sol"
        id: test

  test-fuzz:
    strategy:
      fail-fast: true
    name: Test Fuzz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.3.1

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test --match-path "test/fuzz/**/*.sol"
        id: test

 
